name: hacking-dask
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dask=2021.04.1
  - distributed=2021.04.1
  # JupyterLab + extensions
  - jupyterlab>=3
  - dask-labextension
  - ipywidgets