name: hacking-dask
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dask=2021.04.1
  - python-graphviz
  - imageio
  - scipy
  - matplotlib
  - pyarrow
  # JupyterLab + extensions
  - jupyterlab>=3
  - dask-labextension
  - ipywidgets
  - pip:
    - git+https://github.com/dask/distributed.git@aa9f8d92bf22abb97a913afe16db726868571e9c