name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Build and cache on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }}

  check-os:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: binder/environment.yml
          activate-environment: hacking-dask
          auto-activate-base: false